Repository aasimrazajatoi/groovy-scripts, pull requests merged in 2022-10, with the labels that each got.

#1 changed port number
  webserver.groovy
Labels: hacktoberfest-accept

#2 made some changes in groovy script
  reading files.groovy
Labels: hacktoberfest-accept

#3 Increasing runtime readability.
  reading files.groovy
Labels: hacktoberfest-accept, hacktoberfest-accepted

#4 Adding more details in HTML body.
  webserverIndex.groovy
Labels: hacktoberfest-accepted

#5 file changed
  reading files.groovy
  webserverIndex.groovy
Labels: hacktoberfest-accept

#6 bug fixed
  webserverIndex.groovy
Labels: hacktoberfest-accepted

#7 fixed error with variables
  reading files.groovy
Labels: hacktoberfest-accepted

#8 changed title
  webserverIndex.groovy
Labels: hacktoberfest-accepted
